constants:
  jwt:
    issuer: green@green.com
    schema: Bearer

    claim-key: signedUser

    header-key: Authorization
    secret-key: DaeguGreenArtAcademyClass502RoomForJavaSpringBootFighting

    access-token-cookie-name: access-token


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8888/eureka

server:
  port: 8181
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  application:
    name: scg2
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user
              uri: lb://mujiuniv-be-user
              predicates:
                - Path=/api/account/**
                - Path=/pic/profile/**
                - Path=/api/mypage/**

            - id: not-user
              uri: lb://mujiuniv-be-not-user
              predicates:
                - Path=/api/notice/**
                - Path=/api/schedule
                - Path=/api/course/**
                - Path=/api/application
                - Path=/api/student/**
                - Path=/api/professor/**
                - Path=/api/staff/**


  jackson:
    default-property-inclusion: non_null